<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfaluqo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfaluqo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXfaluqo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXfaluqo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXfaluqo\appProdProjectContainer([
    'container.build_hash' => 'Xfaluqo',
    'container.build_id' => '3d552026',
    'container.build_time' => 1589184604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfaluqo');
